#!/bin/bash

# Creating filesystems
mkfs.vfat -F32 /dev/nvme0n1p1
mkswap /dev/nvme0n1p2
swapon /dev/nvme0n1p2
mkfs.ext4 -F /dev/nvme0n1p3
#mkfs.ext4 -F /dev/nvme0n1p4

# Mounting partitions and creating folders
mount /dev/nvme0n1p3 /mnt
mkdir /mnt/boot
mkdir /mnt/home
mount -o uid=0,gid=0,fmask=0077,dmask=0077 /dev/nvme0n1p1 /mnt/boot
mount /dev/nvme0n1p4 /mnt/home

# Edit pacman configuration
sed -i 's/^#Color/Color/' /etc/pacman.conf
sed -i 's/^#ParallelDownloads = 5/ParallelDownloads = 10/' /etc/pacman.conf

# Updating pacman
pacman -Sy

# Installing Arch Base
pacstrap -K /mnt base base-devel linux linux-firmware nano

# Generating fstab file on new environment
genfstab -U /mnt >> /mnt/etc/fstab

# Chroot into new environment
arch-chroot /mnt
